// This file is auto-generated by GitHub Actions during deployment.
// For local development, it shows 'dev' as the version.
// Do not commit changes to this file - it will be overwritten on deploy.

export const VERSION = 'dev';
export const BUILD_DATE = 'local';
